/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as StartImport } from './routes/start'
import { Route as AppImport } from './routes/_app'
import { Route as IndexImport } from './routes/index'

// Create Virtual Routes

const AppSettingLazyImport = createFileRoute('/_app/setting')()
const AppReferralLazyImport = createFileRoute('/_app/referral')()
const AppMintLazyImport = createFileRoute('/_app/mint')()
const AppHomeLazyImport = createFileRoute('/_app/home')()
const AppBoardLazyImport = createFileRoute('/_app/board')()
const AppAboutLazyImport = createFileRoute('/_app/about')()

// Create/Update Routes

const StartRoute = StartImport.update({
  path: '/start',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/start.lazy').then((d) => d.Route))

const AppRoute = AppImport.update({
  id: '/_app',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const AppSettingLazyRoute = AppSettingLazyImport.update({
  path: '/setting',
  getParentRoute: () => AppRoute,
} as any).lazy(() => import('./routes/_app.setting.lazy').then((d) => d.Route))

const AppReferralLazyRoute = AppReferralLazyImport.update({
  path: '/referral',
  getParentRoute: () => AppRoute,
} as any).lazy(() => import('./routes/_app.referral.lazy').then((d) => d.Route))

const AppMintLazyRoute = AppMintLazyImport.update({
  path: '/mint',
  getParentRoute: () => AppRoute,
} as any).lazy(() => import('./routes/_app.mint.lazy').then((d) => d.Route))

const AppHomeLazyRoute = AppHomeLazyImport.update({
  path: '/home',
  getParentRoute: () => AppRoute,
} as any).lazy(() => import('./routes/_app.home.lazy').then((d) => d.Route))

const AppBoardLazyRoute = AppBoardLazyImport.update({
  path: '/board',
  getParentRoute: () => AppRoute,
} as any).lazy(() => import('./routes/_app.board.lazy').then((d) => d.Route))

const AppAboutLazyRoute = AppAboutLazyImport.update({
  path: '/about',
  getParentRoute: () => AppRoute,
} as any).lazy(() => import('./routes/_app.about.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_app': {
      preLoaderRoute: typeof AppImport
      parentRoute: typeof rootRoute
    }
    '/start': {
      preLoaderRoute: typeof StartImport
      parentRoute: typeof rootRoute
    }
    '/_app/about': {
      preLoaderRoute: typeof AppAboutLazyImport
      parentRoute: typeof AppImport
    }
    '/_app/board': {
      preLoaderRoute: typeof AppBoardLazyImport
      parentRoute: typeof AppImport
    }
    '/_app/home': {
      preLoaderRoute: typeof AppHomeLazyImport
      parentRoute: typeof AppImport
    }
    '/_app/mint': {
      preLoaderRoute: typeof AppMintLazyImport
      parentRoute: typeof AppImport
    }
    '/_app/referral': {
      preLoaderRoute: typeof AppReferralLazyImport
      parentRoute: typeof AppImport
    }
    '/_app/setting': {
      preLoaderRoute: typeof AppSettingLazyImport
      parentRoute: typeof AppImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  AppRoute.addChildren([
    AppAboutLazyRoute,
    AppBoardLazyRoute,
    AppHomeLazyRoute,
    AppMintLazyRoute,
    AppReferralLazyRoute,
    AppSettingLazyRoute,
  ]),
  StartRoute,
])

/* prettier-ignore-end */
